server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Expense?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  # 指定 MyBatis 的 XML 映射文件的位置，mapping/*Mapper.xml 表示 MyBatis 会去 resources/mapping 目录下查找所有以 Mapper 结尾的 xml 文件，作为映射文件。
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.dododo.entity

#日志配置 无特殊需求无需更改
logging:
  level:
    root: info
    org.dododo: debug
#    org.apache.catalina: INFO
#    org.apache.commons.beanutils.converters: INFO
#    org.apache.coyote.http11.Http11Processor: INFO
#    org.apache.http: INFO
#    org.apache.tomcat: INFO
#    org.springframework: INFO

  file:
    path: D:/programing/java-basics/logs
    name: debug.log

